app = "fde-live-translate-ai-oktavianusludiro"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  TRANSLATION_DB_PATH = "/data/translations.db"

[mounts]
  source = "translations_data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
